language: php
php:
    - '7.3'
    - '7.4'

sudo: false

cache:
    directories:
        - $HOME/.composer

env:
    - SYMFONY_VERSION=4.3.*
    - SYMFONY_VERSION=4.4.*
    - SYMFONY_VERSION=5.0.*

matrix:
    fast_finish: true

before_install:
    - composer selfupdate
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/framework-bundle:$SYMFONY_VERSION; fi

install:
    - composer install

script: php vendor/bin/phpunit
