# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        strategy:
            matrix:
                php: [7.3, 7.4]
                symfony: [4.3, 4.4, 4.5]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: MongoDB in GitHub Actions
              uses: supercharge/mongodb-github-action@1.2.0

            - name: Setup PostgreSQL
              uses: Harmon758/postgresql-action@v1.0.0
              with:
                  postgresql version: 11
                  postgresql db: test-db
                  postgresql user: postgres
                  postgresql password: postgres

            - name: Composer Install
              uses: php-actions/composer@v1

            - name: setup-php
              uses: khs1994-docker/actions-setup-php@0.0.1
              with:
                  php_version: ${{ matrix.php }}

            - name: PHPUnit Tests
              uses: php-actions/phpunit@v1
              with:
                  config: phpunit.xml.dist
                  memory: 256M
                  args: |
                    export ORM_DATABASE_DSN=postgres://postgres:postgres@postgres:5432/test-db
                    export ODM_SERVER=mongodb://mongo:27017
                    export ODM_DATABASE=test-db
                    php vendor/bin/phpunit
